// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiLEUmNCxC3fN8_JxIzIOlV-z9nRQhgzI',
    appId: '1:469141566058:web:104c0e29036cd6850fd013',
    messagingSenderId: '469141566058',
    projectId: 'chat-app-bd002',
    authDomain: 'chat-app-bd002.firebaseapp.com',
    storageBucket: 'chat-app-bd002.firebasestorage.app',
    measurementId: 'G-HR5NHKGYL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLksr3NDCwyAc_WY4e7lmOsK_7VAqci8k',
    appId: '1:469141566058:android:f4aae7bbcfc1026b0fd013',
    messagingSenderId: '469141566058',
    projectId: 'chat-app-bd002',
    storageBucket: 'chat-app-bd002.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh8_PFMJ-L5aD-a3OoXBUDYdyee8VS7HY',
    appId: '1:469141566058:ios:54d8e0d663a04dde0fd013',
    messagingSenderId: '469141566058',
    projectId: 'chat-app-bd002',
    storageBucket: 'chat-app-bd002.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh8_PFMJ-L5aD-a3OoXBUDYdyee8VS7HY',
    appId: '1:469141566058:ios:54d8e0d663a04dde0fd013',
    messagingSenderId: '469141566058',
    projectId: 'chat-app-bd002',
    storageBucket: 'chat-app-bd002.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiLEUmNCxC3fN8_JxIzIOlV-z9nRQhgzI',
    appId: '1:469141566058:web:f77ece04b40db2d50fd013',
    messagingSenderId: '469141566058',
    projectId: 'chat-app-bd002',
    authDomain: 'chat-app-bd002.firebaseapp.com',
    storageBucket: 'chat-app-bd002.firebasestorage.app',
    measurementId: 'G-FWMG9M5DT0',
  );
}
